name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential cmake libgtest-dev
    - name: Build tests
      run: mkdir build && cd build && cmake .. && make
    - name: Run tests
      run: cd build && ./matrix_test_rudakov
